const data = {
  users: [],
  employees: [],
  timeEntries: [],
  historicTimeEntries: [],
  stockAlertConfig: { defaultMinStock: 8, enabledByDefault: false },
  categories: [],
  catalog: [],
  salesByDay: [],
  categoryRevenue: [],
  topEmployees: [],
  hourlyTraffic: [],
  goals: [],
  settingsSections: [
    { id: "business", group: "Negocio", label: "Datos del negocio", desc: "Nombre, RFC y dirección", icon: "Sparkle", kind: "form", fields: [] },
    { id: "hours", group: "Negocio", label: "Horarios y días", desc: "Días de operación y horas pico", icon: "Clock", kind: "hours", schedule: [] },
    { id: "receipt", group: "Negocio", label: "Ticket / recibo", desc: "Personaliza el comprobante impreso", icon: "Receipt", kind: "receipt" },
    { id: "tax", group: "Negocio", label: "Impuestos", desc: "IVA y tasas aplicables", icon: "Tag", kind: "tax", rate: 16, includedInPrice: true },
    { id: "services", group: "Catálogo", label: "Servicios", desc: "Edita servicios del salón", icon: "Sparkle", kind: "catalog-list", filter: "S" },
    { id: "products", group: "Catálogo", label: "Productos retail", desc: "Productos para reventa", icon: "Box", kind: "catalog-list", filter: "P" },
    { id: "categories", group: "Catálogo", label: "Categorías", desc: "Agrupa servicios y productos", icon: "Tag", kind: "categories" },
    { id: "promos", group: "Catálogo", label: "Promociones", desc: "Descuentos guardados", icon: "Tag", kind: "promos", promos: [] },
    { id: "users", group: "Equipo", label: "Usuarios y PINs", desc: "Acceso a la terminal", icon: "Users", kind: "users" },
    { id: "roles", group: "Equipo", label: "Roles y permisos", desc: "Quién puede hacer qué", icon: "Lock", kind: "roles", permissions: [] },
    { id: "goals", group: "Equipo", label: "Metas y bonos", desc: "Configura objetivos del mes", icon: "Trophy", kind: "goals" },
    { id: "commissions", group: "Equipo", label: "Comisiones", desc: "Porcentaje por servicio/producto", icon: "Cash", kind: "commissions", rows: [] },
    { id: "lock", group: "Terminal", label: "Tiempo de bloqueo", desc: "Auto-bloqueo por inactividad", icon: "Lock", kind: "lock-time" },
    { id: "payments", group: "Terminal", label: "Métodos de pago", desc: "Habilita formas de cobro", icon: "Card", kind: "payments", methods: [] },
    { id: "appearance", group: "Terminal", label: "Apariencia", desc: "Tema, color y densidad", icon: "Sparkle", kind: "appearance" },
    { id: "backup", group: "Terminal", label: "Copias de seguridad", desc: "Respaldo automático en la nube", icon: "Box", kind: "backup" },
  ],
};

export default data;